name: lite2_sim
urdf_path: src/simulation/robots/lite2_description/urdf/robot.urdf
robot_params:
  total_mass: 10
  total_inertia: [ 0.24, 0, 0, 0, 0.80, 0, 0, 0, 1.0 ] 
  body_mass: 5.298
  body_size: [0.234, 0.184, 0.1]
  body_inertia: [0.0096, 0, 0, 0, 0.014, 0, 0, 0, 0.0195 ]
  links_inertia: [[0.00014538, 8.1579e-07, -1.264e-05, 8.1579e-07, 0.00024024,1.3443e-06,-1.264e-05, 1.3443e-06, 0.00013038],
                  [0.001, -2.5e-06, -0.000112, -2.5e-06, 0.00116, 3.75e-07, -0.000112, 3.75e-07, 0.000268],
                  [0.000668, -1.2e-08,6.91e-06,-1.2e-08,6.86e-04, 5.65e-09, 6.91e-06,  5.65e-09, 3.155e-05]] # for one leg
  links_mass: [0.428, 0.61, 0.145] # for one leg
  links_com_pos: [[-0.0047, -0.0091, -0.0018], [-0.00523, -0.0216, -0.0273], [0.00585, 0, -0.12]] # for FL leg
  body_height: 0.26
  abad_location: [0.175, 0.055, 0]
  hip_l: 0.081
  upper_l: 0.18
  lower_l: 0.18

  velocity:
    # com_offset: [ -0.005, 0.0022, 0.000515 ] # zang mpc
    com_offset: [ 0.005, 0.00145, 0.000515 ] # vel mode
  position:
    com_offset: [ -0.005, 0.0024, 0.000515 ] # pos mode
  walk:
    com_offset: [ -0.005, 0.0012, 0.000515 ] # walk mode
    # com_offset: [ -0.01, 0.003, 0.000515 ] # mpc/walk
  advanced_trot:
    # com_offset: [ -0.004, 0.00145, 0.000515 ] # vel mode
    # com_offset: [ 0.0, 0.00195, 0.000515 ] # yh-mpc
    com_offset: [ -0.005, 0., 0. ] # only for test
  
  hip_offset: [ [ 0.175, -0.055, 0. ],
                [ 0.175, 0.055, 0. ],
                [ -0.175, -0.055, 0. ],
                [ -0.175, 0.055, 0. ] ]
  default_hip_positions: [ [ 0.175, -0.135, 0 ],
                           [ 0.175, 0.135, 0 ],
                           [ -0.175, -0.135, 0 ],
                           [ -0.175, 0.135, 0 ] ]
  
  default_standup_angle:
    ab: 0
    hip: 0.82
    knee: -1.5

  default_sitdown_angle:
    ab: -0.167136
    hip: 0.934969
    knee: -2.54468

motor_params:
  # kps: [ 100,100,100 ]
  # kds: [ 1.0,1.0,1.0 ]
  joint_directions: [ -1,-1,-1, 1,-1,-1, -1,-1,-1, 1,-1,-1 ]
  joint_offsets: [ 0,0,0, 0,0,0, 0,0,0, 0,0,0 ]
  # stand_angle: [ 0,0.67,-1.25 ]

  abad_p: 100.0
  abad_d: 1.0
  hip_p: 100.0
  hip_d: 2.0
  knee_p: 100.0
  knee_d: 2.0


controller_params:
  # mode: 0 # VEL_MODE
  # mode: 1 # POS_MODE
  # mode: 2 # WALK_LOCOMOTION
  mode: 3 # ADVANCED_TROT

# is simulate or not
is_sim: true
